//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeServe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class weserveEntities : DbContext
    {
        public weserveEntities()
            : base("name=weserveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbservice> tbservices { get; set; }
        public virtual DbSet<tbbooking> tbbookings { get; set; }
        public virtual DbSet<TbUser> TbUsers { get; set; }
    
        public virtual ObjectResult<Get_Allbookings_Result> Get_Allbookings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Allbookings_Result>("Get_Allbookings");
        }
    
        public virtual ObjectResult<Get_Bookings_Result> Get_Bookings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Bookings_Result>("Get_Bookings");
        }
    
        public virtual ObjectResult<Fetch_Bookings_Result> Fetch_Bookings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fetch_Bookings_Result>("Fetch_Bookings");
        }
    
        public virtual int Edit_Booking(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Edit_Booking", idParameter);
        }
    
        public virtual ObjectResult<getConfirmations_Result> getConfirmations(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getConfirmations_Result>("getConfirmations", useridParameter);
        }
    
        public virtual ObjectResult<getConfirmedBookings_Result> getConfirmedBookings(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getConfirmedBookings_Result>("getConfirmedBookings", usernameParameter);
        }
    
        public virtual ObjectResult<fetchConfirmedBookings_Result> fetchConfirmedBookings(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fetchConfirmedBookings_Result>("fetchConfirmedBookings", usernameParameter);
        }
    }
}
