//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeServe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbbooking
    {
        public int Id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> serviceid { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> bookdate { get; set; }
        public Nullable<int> confirmstatus { get; set; }
    }
}
